<a href="https://colab.research.google.com/github/levutb2004/building-a-neural-network/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

NUMPY

In [2]:
np1 = np.random.rand(3,4)
np1

array([[0.72808677, 0.98403077, 0.34568546, 0.37632523],
       [0.62646819, 0.67573556, 0.23704693, 0.84494029],
       [0.47047565, 0.75544561, 0.94829087, 0.70054152]])

In [3]:
np1.dtype

dtype('float64')

TENSORS


In [4]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.3174,  0.0545, -0.0318,  0.8469],
        [-0.7009,  0.8659,  1.7377,  0.2220],
        [-0.2042, -0.0854,  2.5090,  0.4858]])

In [5]:
tensor_3d = torch.randn(2,3,4)
tensor_3d

tensor([[[-1.1370, -0.4906, -1.5932, -1.1708],
         [-0.0272, -1.2884,  0.0987,  1.6787],
         [ 0.6166,  0.0881,  1.1737,  1.0384]],

        [[ 0.5868, -0.1696, -0.0270, -1.1902],
         [-0.9248,  1.0897, -0.1553, -0.4332],
         [ 0.4701, -2.2563,  0.1579, -0.7502]]])

In [6]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7281, 0.9840, 0.3457, 0.3763],
        [0.6265, 0.6757, 0.2370, 0.8449],
        [0.4705, 0.7554, 0.9483, 0.7005]], dtype=torch.float64)